<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search utilisateurs</h1>
    <p><?php echo $this->tag->a($this->url->get("utilisateurs/new"), "Create utilisateurs") ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="<?= $this->url->get('utilisateurs/search') ?>" class="form-horizontal" method="get">

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">USERNAME</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("USERNAME", $utilisateur->USERNAME, ["size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">EMAIL</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("EMAIL", $utilisateur->EMAIL, ["size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>





    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("search", "Search", ["class" => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
