<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("utilisateurs"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create utilisateurs</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('utilisateurs/create') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">USERNAME</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("USERNAME", $utilisateur->USERNAME, ["size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">EMAIL</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("EMAIL", $utilisateur->EMAIL, ["size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">PASSWORD</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("PASSWORD", $utilisateur->PASSWORD, ["size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRole" class="col-sm-2 control-label">ROLE</label>
    <div class="col-sm-10">
        <select id="fieldRole" name="ROLE" class="form-control">
            <option value="Admin">Admin</option>
            <option value="Vendeur">Vendeur</option>
            <option value="Magasinier">Magasinier</option>
        </select>
    </div>
</div>




    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
