<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search ventes</h1>
    <p><?php echo $this->tag->a($this->url->get("ventes/new"), "Create ventes") ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="<?= $this->url->get('ventes/search') ?>" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldIdVente" class="col-sm-2 control-label">ID Of VENTE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_VENTE", $vente->ID_VENTE, ["size" => 30, "class" => "form-control", "id" => "fieldIdVente"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdUtilisateur" class="col-sm-2 control-label">ID Of UTILISATEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_UTILISATEUR", $vente->ID_UTILISATEUR, ["size" => 30, "class" => "form-control", "id" => "fieldIdUtilisateur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdClient" class="col-sm-2 control-label">ID Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_CLIENT", $vente->ID_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldIdClient"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateVente" class="col-sm-2 control-label">DATE Of VENTE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputDate("DATE_VENTE", $vente->DATE_VENTE, ["class" => "form-control", "id" => "fieldDateVente"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("search", "Search", ["class" => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
