<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("ventes"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create ventes</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('ventes/create') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdUtilisateur" class="col-sm-2 control-label">ID Of UTILISATEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_UTILISATEUR", $vente->ID_UTILISATEUR, ["size" => 30, "class" => "form-control", "id" => "fieldIdUtilisateur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdClient" class="col-sm-2 control-label">ID Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_CLIENT", $vente->ID_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldIdClient"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateVente" class="col-sm-2 control-label">DATE Of VENTE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputDate("DATE_VENTE", $vente->DATE_VENTE, ["class" => "form-control", "id" => "fieldDateVente"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
