<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search produits</h1>
    <p><?php echo $this->tag->a($this->url->get("produits/new"), "Create produits") ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="<?= $this->url->get('produits/search') ?>" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldIdProduit" class="col-sm-2 control-label">ID Of PRODUIT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_PRODUIT", $produit->ID_PRODUIT, ["size" => 30, "class" => "form-control", "id" => "fieldIdProduit"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdCategorie" class="col-sm-2 control-label">ID Of CATEGORIE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_CATEGORIE", $produit->ID_CATEGORIE, ["size" => 30, "class" => "form-control", "id" => "fieldIdCategorie"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNomProduit" class="col-sm-2 control-label">NOM Of PRODUIT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("NOM_PRODUIT", $produit->NOM_PRODUIT, ["size" => 30, "class" => "form-control", "id" => "fieldNomProduit"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("search", "Search", ["class" => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
