<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("produits"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create produits</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('produits/create') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdCategorie" class="col-sm-2 control-label">ID Of CATEGORIE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_CATEGORIE", $produit->ID_CATEGORIE, ["size" => 30, "class" => "form-control", "id" => "fieldIdCategorie"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNomProduit" class="col-sm-2 control-label">NOM Of PRODUIT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("NOM_PRODUIT", $produit->NOM_PRODUIT, ["size" => 30, "class" => "form-control", "id" => "fieldNomProduit"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
