<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("stocks"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit stocks</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('stocks/save') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdProduit" class="col-sm-2 control-label">ID Of PRODUIT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_PRODUIT", $stock->ID_PRODUIT, ["size" => 30, "class" => "form-control", "id" => "fieldIdProduit"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantiteStock" class="col-sm-2 control-label">QUANTITE Of STOCK</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("QUANTITE_STOCK", $stock->QUANTITE_STOCK, ["size" => 30, "class" => "form-control", "id" => "fieldQuantiteStock"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateMisejour" class="col-sm-2 control-label">DATE Of MISEJOUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputDate("DATE_MISEJOUR", $stock->DATE_MISEJOUR, ["class" => "form-control", "id" => "fieldDateMisejour"]) ?>
    </div>
</div>


    <?php echo $this->tag->inputHidden("id", $stock->ID_STOCK) ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
