<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("clients"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit clients</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('clients/save') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldNomClient" class="col-sm-2 control-label">NOM Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("NOM_CLIENT", $client->NOM_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldNomClient"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrenomClient" class="col-sm-2 control-label">PRENOM Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("PRENOM_CLIENT", $client->PRENOM_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldPrenomClient"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAdresseClient" class="col-sm-2 control-label">ADRESSE Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ADRESSE_CLIENT", $client->ADRESSE_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldAdresseClient"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTelephoneClient" class="col-sm-2 control-label">TELEPHONE Of CLIENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("TELEPHONE_CLIENT", $client->TELEPHONE_CLIENT, ["size" => 30, "class" => "form-control", "id" => "fieldTelephoneClient"]) ?>
    </div>
</div>


    <?php echo $this->tag->inputHidden("id", $client->ID_CLIENT) ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
