<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>Search approvisionnements</h1>
    <p><?php echo $this->tag->a($this->url->get("approvisionnements/new"), "Create approvisionnements") ?></p>
</div>

<?php echo $this->getContent() ?>

<?php echo $this->flash->output() ?>

<form action="<?= $this->url->get('approvisionnements/search') ?>" class="form-horizontal" method="get">
    <div class="form-group">
    <label for="fieldIdApprovisionnement" class="col-sm-2 control-label">ID Of APPROVISIONNEMENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_APPROVISIONNEMENT", $approvisionnement->ID_APPROVISIONNEMENT, ["size" => 30, "class" => "form-control", "id" => "fieldIdApprovisionnement"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdProduit" class="col-sm-2 control-label">ID Of PRODUIT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_PRODUIT", $approvisionnement->ID_PRODUIT, ["size" => 30, "class" => "form-control", "id" => "fieldIdProduit"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldIdFournisseur" class="col-sm-2 control-label">ID Of FOURNISSEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_FOURNISSEUR", $approvisionnement->ID_FOURNISSEUR, ["size" => 30, "class" => "form-control", "id" => "fieldIdFournisseur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantiteApprovisionnement" class="col-sm-2 control-label">QUANTITE Of APPROVISIONNEMENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("QUANTITE_APPROVISIONNEMENT", $approvisionnement->QUANTITE_APPROVISIONNEMENT, ["size" => 30, "class" => "form-control", "id" => "fieldQuantiteApprovisionnement"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrixUnitaireAchat" class="col-sm-2 control-label">PRIX Of UNITAIRE Of ACHAT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputNumeric("PRIX_UNITAIRE_ACHAT", $approvisionnement->PRIX_UNITAIRE_ACHAT, ["class" => "form-control", "id" => "fieldPrixUnitaireAchat"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateApprovisionnement" class="col-sm-2 control-label">DATE Of APPROVISIONNEMENT</label>
    <div class="col-sm-10">
        <?= $this->tag->inputDate("DATE_APPROVISIONNEMENT", $approvisionnement->DATE_APPROVISIONNEMENT, ["class" => "form-control", "id" => "fieldDateApprovisionnement"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("search", "Search", ["class" => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
