<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("concerner"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create concerner</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('concerner/create') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldIdVente" class="col-sm-2 control-label">ID Of VENTE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ID_VENTE", $concerner->ID_VENTE, ["size" => 30, "class" => "form-control", "id" => "fieldIdVente"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldQuantiteVendue" class="col-sm-2 control-label">QUANTITE Of VENDUE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("QUANTITE_VENDUE", $concerner->QUANTITE_VENDUE, ["size" => 30, "class" => "form-control", "id" => "fieldQuantiteVendue"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrixUnitaireVendue" class="col-sm-2 control-label">PRIX Of UNITAIRE Of VENDUE</label>
    <div class="col-sm-10">
        <?= $this->tag->inputNumeric("PRIX_UNITAIRE_VENDUE", $concerner->PRIX_UNITAIRE_VENDUE, ["class" => "form-control", "id" => "fieldPrixUnitaireVendue"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
