<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("fournisseurs"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create fournisseurs</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('fournisseurs/create') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldNomCompletFournisseur" class="col-sm-2 control-label">NOM Of COMPLET Of FOURNISSEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("NOM_COMPLET_FOURNISSEUR", $fournisseur->NOM_COMPLET_FOURNISSEUR, ["size" => 30, "class" => "form-control", "id" => "fieldNomCompletFournisseur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAdresseFournisseur" class="col-sm-2 control-label">ADRESSE Of FOURNISSEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("ADRESSE_FOURNISSEUR", $fournisseur->ADRESSE_FOURNISSEUR, ["size" => 30, "class" => "form-control", "id" => "fieldAdresseFournisseur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailFournisseur" class="col-sm-2 control-label">EMAIL Of FOURNISSEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("EMAIL_FOURNISSEUR", $fournisseur->EMAIL_FOURNISSEUR, ["size" => 30, "class" => "form-control", "id" => "fieldEmailFournisseur"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTelephoneFournisseur" class="col-sm-2 control-label">TELEPHONE Of FOURNISSEUR</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("TELEPHONE_FOURNISSEUR", $fournisseur->TELEPHONE_FOURNISSEUR, ["size" => 30, "class" => "form-control", "id" => "fieldTelephoneFournisseur"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
